config/routes.rb
Stylequiz::Application.routes.draw do
  resources :tests do
    resources :questions, only: [:create, :destroy]
    match '/complete',    to: 'tests#complete'
  end

  root to: 'static_pages#home'
  match '/demo', to: 'tests#new'
  match '/what', to: 'static_pages#whatwedo'
  match '/how', to: 'static_pages#howitworks'
  match '/requests', to: 'static_pages#requestdemo'

end

app/models/question.rb
class Question < ActiveRecord::Base
  attr_accessible :item_a, :item_b, :test_id, :win, :lose
  belongs_to :test

  validates :test_id, presence: true
  validates :item_a, presence: true
  validates :item_b, presence: true
  validates :win, presence: true
  validates :lose, presence: true
  default_scope order: 'questions.created_at ASC'
end

app/models/tagpair.rb
class Tagpair < ActiveRecord::Base
  attr_accessible :item, :tag_a, :tag_b, :link

  validates :item, presence: true
  validates :tag_a, presence: true
  validates :tag_b, presence: true
  validates :link, presence: true
end

app/models/test.rb
class Test < ActiveRecord::Base
  attr_accessible :started
  has_many :questions, dependent: :destroy

  validates :started, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  def create
  	@test = Test.find(params[:test_id])
  	@question = @test.questions.build(params[:question])
  	if @question.save
      if Question.where("test_id = ? ", @question.test_id).count<20
  		  redirect_to @test
      else
        redirect_to test_complete_path(id: @test)
      end
  	else
  		redirect_to root_url
  	end
  end

  def destroy
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def whatwedo
  end

  def howitworks
  end

  def requestdemo
  end
end

app/controllers/tests_controller.rb
class TestsController < ApplicationController
  def new
  	@test = Test.new
  end

  def create
  	@test = Test.new(params[:test])
    if @test.save
      redirect_to @test
    else
      render 'new'
    end
  end

  def show
  	@test = Test.find(params[:id])
    @question = @test.questions.build
    @count = Question.where("test_id = ?", @test.id).count
    @num_a = 1 + rand(99)
    @num_b = 1 + rand(99)
    if @num_b == @num_a
      if @num_b == 100
        @num_b = 1 + rand(98)
      else
        @num_b = @num_b + 1
      end
    end
  end

  def complete
    @test = Test.find(params[:id])
    @results = Question.where("test_id = ?", @test.id)
    
    @win_tagpair_array = Array.new
    @results.each do |result|
      @win_tagpair = Tagpair.where("item = ?", result.win)
      @win_tagpair.each do |tagpair|
        @win_tagpair_array.push tagpair.tag_a + " & " + tagpair.tag_b
      end
    end

    @lose_tagpair_array = Array.new
    @results.each do |result|
      @lose_tagpair = Tagpair.where("item = ?", result.lose)
      @lose_tagpair.each do |tagpair|
        @lose_tagpair_array.push tagpair.tag_a + " & " + tagpair.tag_b
      end
    end
    
    @win_counts = Array.new
    @win_tagpair_array.each do |tagpair|
      @win_counts.push @win_tagpair_array.count(tagpair)
    end
    @lose_counts = Array.new
    @lose_tagpair_array.each do |tagpair|
      @lose_counts.push @lose_tagpair_array.count(tagpair)
    end

    @tagpair_array = Array.new
    @net_counts = Array.new
    @win_tagpair_array.each do |tagpair|
      if !@tagpair_array.include?(tagpair)
        @tagpair_array.push tagpair
        @net = @win_counts[@win_tagpair_array.index(tagpair)]
        if @lose_tagpair_array.include?(tagpair)
          @net = @net - @lose_counts[@lose_tagpair_array.index(tagpair)]
        end
        @net_counts.push @net
      end
    end

    @max_tagpairs = Array.new
    @tagpair_array.each do |tagpair|
      if @net_counts[@tagpair_array.index(tagpair)] > @net_counts.max - 2 && @tagpair_array.count(tagpair) > 0
        if !@max_tagpairs.include?(tagpair)
          @max_tagpairs.push(tagpair)
        end
      end
    end

    @recs = Array.new
    @max_tagpairs.each do |tagpair|
      tags = tagpair.split(" ")
      tag_a = tags.first
      tag_b = tags.last
      @rec_items = Tagpair.where("tag_a = ? and tag_b = ?", tag_a, tag_b)
      @rec_items.each do |rec_item|
        @recs.push rec_item.item
      end
    end
    @recs.shuffle!

    @winners = Array.new
    @results.each do |result|
      if !@winners.include?(result.win)
        @winners.push result.win
      end
    end

    @extras = Array.new
    @winners.each do |winner|
      if !@recs.include?(winner)
        @extras.push winner
      end
    end
    @extras.shuffle!
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/tests_helper.rb
module TestsHelper
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    by susan
  </small>
  <nav>
    <ul>
      <li><%= link_to "Home", root_path %></li>
      <li><%= link_to "Request demo", requests_path %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="navbar-inner">
    <div class="container">
      <%= link_to "TasteSeeker", root_path, id: "logo" %>
      <nav>
        <ul class="nav pull-right">
          <li><%= link_to "Home", root_path %></li>
          <li><%= link_to "What we do", what_path %></li>
          <li><%= link_to "How it works", how_path %></li>
          <li><%= link_to "Request demo", requests_path %></li>
        </ul>
      </nav>
    </div>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
	  <title>TasteSeeker | <%= yield(:title) %></title>
	  <%= stylesheet_link_tag    "application", :media => "all" %>
	  <%= javascript_include_tag "application" %>
	  <%= csrf_meta_tags %>
	  <%= render 'layouts/shim' %>
	  <%= favicon_link_tag 'favicon2.ico' %>
	</head>
	<body>
		<%= render 'layouts/header' %>
    <div class="container">
			<%= yield %>
			<%= render 'layouts/footer' %>
			<%= debug(params) if Rails.env.development? %>
		</div>
	</body>
</html>

app/views/shared/_error_messages.html.erb
<% if @test.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-error">
      The form contains <%= pluralize(@test.errors.count, "error") %>.
    </div>
    <ul>
    <% @test.errors.full_messages.each do |msg| %>
      <li>* <%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/static_pages/home.html.erb
<% provide(:title, 'Home') %>
<h1>
	TasteSeeker
</h1>
<h2>
	Every customer is different. Knowing that is powerful.
</h2>

<div class="row">
	<div align="center">
		<div class="span4">
			<%= link_to image_tag("holly-1.png"), what_path %>
			<h3><%= link_to "What we do", what_path %></h3>
		</div>
		<div class="span4">
			<%= link_to image_tag("holly-2.png"), how_path %>
			<h3><%= link_to "How it works", how_path %></h3>
		</div>
		<div class="span4">
			<%= link_to image_tag("holly-3.png"), requests_path %>
			<h3><%= link_to "Request demo", requests_path %></h3>
		</div>
	</div>
</div>

app/views/static_pages/howitworks.html.erb
<% provide(:title, 'How') %>

<div class="row">
	<div class="span8 offset1">
		<h3>
			How it works
		</h3>
		<br>
		<p>
			The data scientists and physicists on our team draw on their scientific experience to determine the unique personal style of each customer who visits your website. Our TasteSeeker algorithm automatically classifies each product in your inventory according to style. We then analyze customer behavior to determine which styles of products each customer will like best.
			<br><br>
			Below is an example of a "style graph" we created for an online retailer of women's clothing. Our network-based algorithm quickly identified the predominate styles associated with this particular brand. To learn more about how TasteSeeker works, <%=link_to "request a demo", requests_path %>.
		</p>
		<br>
	</div>
</div>

<%= image_tag "stylenet.png" %>

app/views/static_pages/requestdemo.html.erb
<% provide(:title, 'Requests') %>

<div class="row">
	<div class="span8 offset1">
		<h3>
			Request a demo
		</h3>
		<br>
		<p>
			Learn what TasteSeeker can do for your business. We provide customized predictive analytics support for any company with an online store--and we have fun doing it! To request a demo, email us at <%= mail_to "info@tasteseeker.com" %>
		</p>
	</div>
</div>

app/views/static_pages/whatwedo.html.erb
<% provide(:title, 'What') %>

<div class="row">
	<div class="span8 offset1">
		<h3>
			What we do
		</h3>
		<br>
		<p>
			TasteSeeker provides custom analytics for retailers of all sizes. Our recommendation engines boost sales by discovering the unique personal taste of each customer. Our San Francisco-based team includes experienced data scientists, physicists, and startup veterans--but we're also fashion lovers with a sense of fun and a commitment to great customer service!
			<br><br>
			Our case studies for online clothing retailers have shown a 40% increase in sales. Want to see what TasteSeeker can do for your business? <%= link_to "Request a demo", requests_path %>
		</p>
	</div>
</div>